"""empty message

Revision ID: 36339174539e
Revises: 86c6eb7ec4d6
Create Date: 2018-08-28 21:01:17.520788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36339174539e'
down_revision = '86c6eb7ec4d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answers', 'parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
