"""empty message

Revision ID: 7acf1693f891
Revises: b30c6f3a05f0
Create Date: 2018-08-28 20:42:36.746920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acf1693f891'
down_revision = 'b30c6f3a05f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('parent_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'answers', 'answers', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'parent_id')
    # ### end Alembic commands ###
